#weapons:
#  - id: trebuchetSling
#    rangeMin: 3
#    rangeMax: 5
#    canMoveAndAttack: false
#    baseDamage:
#      land: 1
#      water: 1
#      buildings: 1
#    tagDamageOverwrite: archer
#
#unitClasses:
#  - id: trebuchet
#    name: unit_class_name_trebuchet
#    cost: 1100
#    resourceCost: 3
#    movement: wheels
#    moveRange: 5
#    damageMultiplier: 1
#    aiPriority: 1.6
#    weapons:
#      - id: trebuchetSling
#    tags:
#      - trebuchet
#      - type.ground.heavy
#    verbs:
#      - load
#    battleUnitCount: 1
#    passiveMultiplier: 1.5
#    sightRange: 2
#
#
#
#units:
#  - class: trebuchet
#    faction: cherrystone
#    name: unit_name_trebuchet_cherrystone
#    mapAnimation: units/trebuchet/cherrystone/map_trebuchet_cherrystone
#    mapLightSource:
#      sprite: lights_medium
#      scale: [1.0, 1.0]
#      jitter:
#        scale: 1.0
#        frequency: 0.3
#        frequencyVariance: 0.15
#    battleLightSource:
#      sprite: lights_battle_large
#      scale: [0.95, 0.55]
#      jitter:
#        scale: 0.4
#        frequency: 0.3
#        frequencyVariance: 0.15
#    battleAnimation: units/trebuchet/cherrystone/battle_trebuchet_cherrystone
#    smallPortrait: units/trebuchet/cherrystone/portrait_trebuchet_cherrystone_small.png
#    mediumPortrait: units/trebuchet/cherrystone/portrait_trebuchet_cherrystone_medium.png
#    mapSpeed: 4.0
#    grabPos: [16, 17]
#    attackOffset: [50, 0]
#    battlePosOffset: [-21, 0]
#    deathMoveMin: 0
#    deathMoveMax: 0
#    stayAfterDeath: true
#    emotes:
#      idle: idle
#    sounds:
#      attackMap: unitAttack
#      attack: trebuchetAttack
#      attackEffect: trebuchetAttackEffect
#      death: trebuchetDie
#      deathMap: unitDie
#      run: trebuchetEntry
#      runMap: trebuchetMapEntry
#      hit: hitWood
#      hitMap: hitWood
#    attacks:
#      - id: primary
#        hitDelay: 2.0
#        hitSpark: fx/bs_stab_attack
#        ranged: true
#        effect: fx/bs_trebuchet_attack
#        effectPaletteSwaps: true
#        postAttackAnimationSequence: post_attack_idle
#        postAttackHitSequence: post_attack_hit
#        postAttackDeathSequence: post_attack_death
#        effectDelay: 1.8
#
#  - class: trebuchet
#    faction: felheim
#    name: unit_name_trebuchet_felheim
#    mapAnimation: units/trebuchet/felheim/map_trebuchet_felheim
#    mapLightSource:
#      sprite: lights_medium
#      scale: [1.0, 1.0]
#      jitter:
#        scale: 1.0
#        frequency: 0.3
#        frequencyVariance: 0.15
#    battleLightSource:
#      sprite: lights_battle_large
#      scale: [0.95, 0.55]
#      jitter:
#        scale: 0.4
#        frequency: 0.3
#        frequencyVariance: 0.15
#    battleAnimation: units/trebuchet/felheim/battle_trebuchet_felheim
#    smallPortrait: units/trebuchet/felheim/portrait_trebuchet_felheim_small.png
#    mediumPortrait: units/trebuchet/felheim/portrait_trebuchet_felheim_medium.png
#    mapSpeed: 4.0
#    grabPos: [16, 17]
#    attackOffset: [50, 0]
#    battlePosOffset: [-21, 0]
#    deathMoveMin: 0
#    deathMoveMax: 0
#    stayAfterDeath: true
#    emotes:
#      idle: idle
#    sounds:
#      attackMap: unitAttack
#      attack: trebuchetAttack
#      attackEffect: trebuchetAttackEffect
#      death: trebuchetDieBlue
#      deathMap: unitDie
#      run: trebuchetEntryBlue
#      runMap: trebuchetMapEntry
#      hit: hitWood
#      hitMap: hitWood
#    attacks:
#      - id: primary
#        hitDelay: 2.0
#        hitSpark: fx/bs_stab_attack
#        ranged: true
#        effect: fx/bs_trebuchet_attack
#        effectPaletteSwaps: true
#        postAttackAnimationSequence: post_attack_idle
#        postAttackHitSequence: post_attack_hit
#        postAttackDeathSequence: post_attack_death
#        effectDelay: 1.8
#
#
#  - class: trebuchet
#    faction: heavensong
#    name: unit_name_trebuchet_heavensong
#    mapAnimation: units/trebuchet/heavensong/map_trebuchet_heavensong
#    mapLightSource:
#      sprite: lights_medium
#      scale: [1.0, 1.0]
#      jitter:
#        scale: 1.0
#        frequency: 0.3
#        frequencyVariance: 0.15
#    battleLightSource:
#      sprite: lights_battle_large
#      scale: [0.95, 0.55]
#      jitter:
#        scale: 0.4
#        frequency: 0.3
#        frequencyVariance: 0.15
#    battleAnimation: units/trebuchet/heavensong/battle_trebuchet_heavensong
#    smallPortrait: units/trebuchet/heavensong/portrait_trebuchet_heavensong_small.png
#    mediumPortrait: units/trebuchet/heavensong/portrait_trebuchet_heavensong_medium.png
#    mapSpeed: 4.0
#    grabPos: [16, 17]
#    attackOffset: [50, 0]
#    battlePosOffset: [-21, 0]
#    deathMoveMin: 0
#    deathMoveMax: 0
#    stayAfterDeath: true
#    emotes:
#      idle: idle
#    sounds:
#      attackMap: unitAttack
#      attack: trebuchetAttack
#      attackEffect: trebuchetAttackEffect
#      death: trebuchetDie
#      deathMap: unitDie
#      run: trebuchetEntry
#      runMap: trebuchetMapEntry
#      hit: hitWood
#      hitMap: hitWood
#    attacks:
#      - id: primary
#        hitDelay: 2.0
#        hitSpark: fx/bs_stab_attack
#        ranged: true
#        effect: fx/bs_trebuchet_attack
#        effectPaletteSwaps: true
#        postAttackAnimationSequence: post_attack_idle
#        postAttackHitSequence: post_attack_hit
#        postAttackDeathSequence: post_attack_death
#        effectDelay: 1.8
#
#  - class: trebuchet
#    faction: floran
#    name: unit_name_trebuchet_floran
#    mapAnimation: units/trebuchet/floran/map_trebuchet_floran
#    mapLightSource:
#      sprite: lights_medium
#      scale: [1.0, 1.0]
#      jitter:
#        scale: 1.0
#        frequency: 0.3
#        frequencyVariance: 0.15
#    battleLightSource:
#      sprite: lights_battle_large
#      scale: [0.95, 0.55]
#      jitter:
#        scale: 0.4
#        frequency: 0.3
#        frequencyVariance: 0.15
#    battleAnimation: units/trebuchet/floran/battle_trebuchet_floran
#    smallPortrait: units/trebuchet/floran/portrait_trebuchet_floran_small.png
#    mediumPortrait: units/trebuchet/floran/portrait_trebuchet_floran_medium.png
#    mapSpeed: 4.0
#    grabPos: [16, 17]
#    attackOffset: [50, 0]
#    battlePosOffset: [-21, 0]
#    deathMoveMin: 0
#    deathMoveMax: 0
#    stayAfterDeath: true
#    emotes:
#      idle: idle
#    sounds:
#      attackMap: unitAttack
#      attack: trebuchetAttack
#      attackEffect: trebuchetAttackEffect
#      death: trebuchetDieGreen
#      deathMap: unitDie
#      run: trebuchetEntryGreen
#      runMap: trebuchetMapEntry
#      hit: hitWood
#      hitMap: hitWood
#    attacks:
#      - id: primary
#        hitDelay: 2.0
#        hitSpark: fx/bs_stab_attack
#        ranged: true
#        effect: fx/bs_trebuchet_floran_attack
#        postAttackAnimationSequence: post_attack_idle
#        postAttackHitSequence: post_attack_hit
#        postAttackDeathSequence: post_attack_death
#        effectDelay: 1.8
#
#  - class: trebuchet
#    faction: faahri
#    name: unit_name_trebuchet_faahri
#    mapAnimation: units/trebuchet/faahri/map_trebuchet_faahri
#    mapLightSource:
#      sprite: lights_medium
#      scale: [1.0, 1.0]
#      jitter:
#        scale: 1.0
#        frequency: 0.3
#        frequencyVariance: 0.15
#    battleLightSource:
#      sprite: lights_battle_large
#      scale: [0.95, 0.55]
#      jitter:
#        scale: 0.4
#        frequency: 0.3
#        frequencyVariance: 0.15
#    battleAnimation: units/trebuchet/faahri/battle_trebuchet_faahri
#    smallPortrait: units/trebuchet/faahri/portrait_trebuchet_faahri_small.png
#    mediumPortrait: units/trebuchet/faahri/portrait_trebuchet_faahri_medium.png
#    mapSpeed: 4.0
#    grabPos: [16, 17]
#    attackTimingsHack: false
#    attackOffset: [50, 0]
#    battlePosOffset: [-21, 0]
#    deathMoveMin: 0
#    deathMoveMax: 0
#    stayAfterDeath: true
#    emotes:
#      idle: idle
#    sounds:
#      attackMap: unitAttack
#      attack: trebuchetAttackOrange
#      attackEffect: trebuchetAttackEffectOrange
#      death: trebuchetDieOrange
#      deathMap: unitDie
#      run: trebuchetEntry
#      runMap: trebuchetMapEntry
#      hit: hitWood
#      hitMap: hitWood
#    attacks:
#      - id: primary
#        hitDelay: 2.0
#        hitSpark: fx/bs_stab_attack
#        ranged: true
#        effect: fx/bs_trebuchet_faahri_attack
#        postAttackAnimationSequence: post_attack_idle
#        postAttackHitSequence: post_attack_hit
#        postAttackDeathSequence: post_attack_death
#        effectDelay: 1.8
#
#  - class: trebuchet
#    faction: pirates
#    name: unit_name_trebuchet_pirates
#    mapAnimation: units/trebuchet/pirates/map_trebuchet_pirates
#    mapLightSource:
#      sprite: lights_medium
#      scale: [1.0, 1.0]
#      jitter:
#        scale: 1.0
#        frequency: 0.3
#        frequencyVariance: 0.15
#    battleLightSource:
#      sprite: lights_battle_large
#      scale: [0.95, 0.55]
#      jitter:
#        scale: 0.4
#        frequency: 0.3
#        frequencyVariance: 0.15
#    battleAnimation: units/trebuchet/pirates/battle_trebuchet_pirates
#    smallPortrait: units/trebuchet/pirates/portrait_trebuchet_pirates_small.png
#    mediumPortrait: units/trebuchet/pirates/portrait_trebuchet_pirates_medium.png
#    mapSpeed: 4.0
#    grabPos: [16, 17]
#    attackOffset: [50, 0]
#    battlePosOffset: [-21, 0]
#    deathMoveMin: 0
#    deathMoveMax: 0
#    stayAfterDeath: true
#    emotes:
#      idle: idle
#    sounds:
#      attackMap: unitAttack
#      attack: trebuchetAttack
#      attackEffect: trebuchetAttackEffect
#      death: trebuchetDie
#      deathMap: unitDie
#      run: trebuchetEntry
#      runMap: trebuchetMapEntry
#      hit: hitWood
#      hitMap: hitWood
#    attacks:
#      - id: primary
#        hitDelay: 2.0
#        hitSpark: fx/bs_stab_attack
#        ranged: true
#        effect: fx/bs_trebuchet_pirates_attack
#        postAttackAnimationSequence: post_attack_idle
#        postAttackHitSequence: post_attack_hit
#        postAttackDeathSequence: post_attack_death
#        effectDelay: 1.8
